In [1]:
import numpy as np

# Elementwise Operations

**1. Basic Operations**

**with scalars**

In [2]:
a = np.array([1, 2, 3, 4]) #create an array

a + 1

array([2, 3, 4, 5])

In [3]:
a ** 2

array([ 1,  4,  9, 16])

**All arithmetic operates elementwise**

In [4]:
b = np.ones(4) + 1

a - b

array([-1.,  0.,  1.,  2.])

In [5]:
# Matrix multiplication

c = np.diag([1, 2, 3, 4])

print(c * c)
print("*****************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [10]:
# Dot Product
np.dot(a, b)  





20.0

In [11]:
# Elementwise Multiplication
a * b  

array([2., 4., 6., 8.])

In [12]:
# Matrix Multiplication (for 2D arrays)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


np.matmul(A, B)  

array([[19, 22],
       [43, 50]])

What Are Inner Dimensions in Matrix Multiplication?
In matrix multiplication, the inner dimensions refer to the number of columns in the first matrix and the number of rows in the second matrix.

For two matrices A and B:

A has shape 
(
𝑚
×
𝑛
)
(m×n) → 
𝑚
m rows, 
𝑛
n columns

B has shape 
(
𝑝
×
𝑞
)
(p×q) → 
𝑝
p rows, 
𝑞
q columns

For matrix multiplication to be valid, the inner dimensions must be equal:

(
𝑚
×
𝑛
)
@
(
𝑛
×
𝑞
)
=
(
𝑚
×
𝑞
)
(m×n)@(n×q)=(m×q)
If 
𝑛
≠
𝑝
n

=p, the multiplication is not possible.

To multiply a 
2
×
3
2×3 matrix with a 
3
×
4
3×4 matrix, we use matrix multiplication, which is performed using np.matmul() or the @ operator in NumPy.

Matrix Dimensions:
Let A be a 
2
×
3
2×3 matrix.

Let B be a 
3
×
4
3×4 matrix.

The result will be a 
2
×
4
2×4 matrix because the inner dimensions (3) match.

In [13]:
import numpy as np

# 2x3 Matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3x4 Matrix
B = np.array([
    [7, 8, 9, 10],
    [11, 12, 13, 14],
    [15, 16, 17, 18]
])

# Matrix multiplication (result will be 2x4)
C = np.matmul(A, B)  # or A @ B
print(C)

[[ 74  80  86  92]
 [173 188 203 218]]


If the inner dimensions do not match, matrix multiplication is not possible in NumPy, and you'll get an error.

Example of Mismatched Dimensions
If you try to multiply a 
2
×
3
2×3 matrix with another 
2
×
4
2×4 matrix:

In [28]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])  # 2x3 matrix

B = np.array([
    [7, 8, 9, 10],
    [11, 12, 13, 14]
])  # 2x4 matrix

# This will cause an error!
C = np.matmul(A, B)  # or A @ B


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

Possible Fixes
If you want to multiply these matrices, you have a option:

1. Transpose A to Match the Dimensions
If possible, transpose A (A.T) to make its dimensions match:

In [37]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])  # 2x3 matrix

B = np.array([
    [7, 8, 9, 10],
    [11, 12, 13, 14]
])  # 2x4 matrix
C = np.matmul(A.T, B)  # (3x2) @ (2x4) = (3x4)

print(C)

[[ 51  56  61  66]
 [ 69  76  83  90]
 [ 87  96 105 114]]


**comparisions**

In [39]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [40]:
a > b

array([False, False,  True, False])

In [41]:
#array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)

False

In [42]:
np.array_equal(a, c)

True

**Logical Operations**

In [43]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [44]:
np.logical_and(a, b)

array([ True, False, False, False])

**Transcendental functions:**

In [45]:
a = np.arange(5)

np.sin(a)   

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [46]:
np.log(a)

C:\Users\jaiku\AppData\Local\Temp\ipykernel_23124\2987416308.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [47]:
np.exp(a)   #evaluates e^x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

**Shape Mismatch**

In [48]:
a = np.arange(4)

a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions

**computing sums**

In [49]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [50]:


x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [51]:
x.sum(axis=0)   #columns first dimension

array([3, 3])

In [52]:
x.sum(axis=1)  #rows (second dimension)

array([2, 4])

**Other reductions**

In [53]:
x = np.array([1, 3, 2])
x.min()

1

In [54]:
x.max()

3

In [55]:
x.argmin()  # index of minimum element

0

In [56]:
x.argmax()# index of maximum element

1

**Logical Operations**

In [57]:
np.all([True, True, False])

False

In [58]:
np.any([True, False, False])

True

In [59]:
#Note: can be used for array comparisions
a = np.zeros((50, 50))
np.any(a != 0)

False

In [60]:
np.all(a == a)

True

In [61]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

**Statistics**

In [62]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [63]:
np.median(x)

1.5

In [64]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [65]:
x.std()          # full population standard dev.

0.82915619758885

Data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.

In [66]:
#load data into numpy array object
data = np.loadtxt('populations.txt')

In [67]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [68]:
year, hares, lynxes, carrots = data.T #columns to variables
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [69]:
#The mean population over time
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [70]:
#sample standard deviations
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [71]:
#which species has the highest population each year?

np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

# Broadcasting

Basic operations on numpy arrays (addition, etc.) are elementwise

This works on arrays of the same size.
    Nevertheless, It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays     so that they all have the same size: this conversion is called broadcasting.

The image below gives an example of broadcasting:

![title](broadcasting.png)

In [72]:
a = np.tile(np.arange(0, 40, 10), (3,1))
print(a)

print("*************")
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [73]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [74]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [75]:
a = np.arange(0, 40, 10)
a.shape

(4,)

In [76]:
a = a[:, np.newaxis]  # adds a new axis -> 2D array
a.shape

(4, 1)

In [77]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [78]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# Array Shape Manipulation

**Flattening**

In [79]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel() #Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

array([1, 2, 3, 4, 5, 6])

In [80]:
a.T #Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [81]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

**Reshaping**

The inverse operation to flattening:

In [82]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [83]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [84]:
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

**Note and       Beware: reshape may also return a copy!:**

In [99]:
a = np.zeros((3, 2))  # Creates a 3x2 matrix filled with zeros
b = a.T.reshape(3*2)  # Transposes a (2x3) and reshapes to a 1D array of size 6
b[0] = 50  # Modifies the first element of b
print(a)  # What happens to a?
# Does b Affect a?
# No, b does not modify a because of how NumPy reshapes transposed arrays.
# If you modify b[0], it does not affect a. The reason is that when you reshape a transposed array, it creates a new copy instead of a view.

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

**Adding a Dimension**

Indexing with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on

In [100]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [101]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

**Dimension Shuffling**

In [102]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

(4, 3, 2)

In [103]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [104]:
a[0, 2, 1]

5

**Resizing**

In [105]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

However, it must not be referred to somewhere else:

In [106]:
b = a
a.resize((4,)) 

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

**Sorting Data**

In [107]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [108]:
#in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [109]:
#sorting with fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [110]:
a[j]

array([1, 2, 3, 4])