Intrinsic vs. Extrinsic Arrays in NumPy

Intrinsic Arrays
Intrinsic arrays are arrays that are created using built-in NumPy functions such as zeros(), ones(), full(), and arange(). These functions generate arrays with predefined values without requiring the user to provide explicit data.

Examples of Intrinsic Arrays
Using zeros() to create an array filled with zeros

In [1]:
import numpy as np
intrinsic_array = np.zeros((3, 3))
print(intrinsic_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Using ones() to create an array filled with ones

In [2]:
intrinsic_array = np.ones((3, 3))
print(intrinsic_array)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Using arange() to create a sequence

In [3]:
intrinsic_array = np.arange(10)
print(intrinsic_array)


[0 1 2 3 4 5 6 7 8 9]


Extrinsic Arrays
Extrinsic arrays, on the other hand, are created from external sources such as lists, tuples, or files. These arrays do not have predefined values; instead, they take their values from user input, data files, or other sources.

Creating an array from a Python list

In [4]:
extrinsic_array = np.array([10, 20, 30, 40])
print(extrinsic_array)


[10 20 30 40]


Creating an array from a tuple

In [5]:
extrinsic_array = np.array((5, 10, 15, 20))
print(extrinsic_array)


[ 5 10 15 20]


# Converting Between Intrinsic and Extrinsic Arrays

Converting an Intrinsic Array to an Extrinsic Array

You can convert an intrinsic array to an extrinsic one by converting it into a Python list using .tolist()

In [6]:
intrinsic_array = np.ones((2, 2))  # Creating an intrinsic array
extrinsic_list = intrinsic_array.tolist()  # Converting to extrinsic (Python list)
print(extrinsic_list)


[[1.0, 1.0], [1.0, 1.0]]


Converting an Extrinsic Array to an Intrinsic Array

You can convert an extrinsic array (list, tuple, or external data) into an intrinsic NumPy array using np.array().

In [7]:
extrinsic_list = [[2, 4, 6], [8, 10, 12]]  # Python list (extrinsic)
intrinsic_array = np.array(extrinsic_list)  # Converting to NumPy intrinsic array
print(intrinsic_array)


[[ 2  4  6]
 [ 8 10 12]]


In [8]:
# Type	Definition	Example
# Intrinsic Arrays	Created using built-in NumPy functions like zeros(), ones(), arange(), etc.	np.zeros((3,3))
# Extrinsic Arrays	Created from external data sources like lists, tuples, or files.	np.array([10, 20, 30])
# Conversion (Intrinsic → Extrinsic)	Convert to a Python list using .tolist()	array.tolist()
# Conversion (Extrinsic → Intrinsic)	Convert to a NumPy array using np.array()	np.array(list)